name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Run tests
      run: |
        poetry run pytest -v

  build-and-deploy:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install poetry
      run: |
        install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Build
      run: |
        poetry build
    - name: Package
      run: |
        ./auto/package

    - uses: hashicorp/setup-terraform@v3
    - name: Deploy
      working-directory: infra
      run: |
        terraform init
        terraform workspace select -or-create dev
        terraform apply -auto-approve
